version: '3'

services:
  fuseki:
    image: "stain/jena-fuseki"
    ports:
     - "3030:3030"
    volumes:
      - fuseki-data:/fuseki
    environment:
      - ADMIN_PASSWORD=gnugnu1234
  runic-text:
    build: runic-text
    ports:
     - "8080:80"

volumes:
  fuseki-data:

